config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }

  resources :products do
    resources :comments
  end
  resources :users
  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/landing_page'
  post 'simple_pages/thank_you'
  root 'simple_pages#landing_page'
  post 'payments/create'

  resources :orders, only: %i[index show create destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index;
  end

  def landing_page
    @products = Product.limit(3)
    @featured_product = Product.first
  end

  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    UserMailer.contact_form(@email, @name, @message).deliver_now
  end
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/simple_pages/_form.html.erb
<%= flash[:notice] %>

<%= form_with(url: simple_pages_thank_you_path, local: true) do |form| %>
<div class="row styleRow">
  <div class="form-group labelA">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "Enter Name",required: "true",pattern:"[A-Za-z-0-9]+\s[A-Za-z-'0-9]+", title:"firstname lastname" %>
  </div>
  <div class="form-group">
    <%= form.label :email, "Email Address" %>
    <%= form.text_field :email, placeholder: "Enter Email",type: "email",required: "true" %>
  </div>
  <div class="form-group">
    <%= form.label :message %>
    <%= form.text_area :message, placeholder: "Enter Message", rows: 5,required: "true" %>
  </div>

  <%= form.submit("Send", class: "btn btn-primary send-btn") %>

</div>

<% end %>

app/views/simple_pages/about.html.erb
<!-- ****** A B O U T M E ****** -->
<!--
<% cache do %>
  <% sleep 2 %>
-->
    <div class="container" id="about">
      <div class="box">
        <div class="header">
          <h1>About Me</h1>
        </div>
        <!-- end header -->
      </div>
      <!-- end boxs -->

      <div class="container" style="margin-bottom: 20px;">
        <div class="row" style="text-align: center;">
          <div class="image col-xs-12 col-sm-6 col-md-4">
            <%= image_tag("abood.jpg", class: "img-responsive") %>
          </div>
          <!-- end image -->

          <div class="Intro col-xs-12 col-sm-6 col-md-4">
            <h2>
              <strong>Introduction</strong>
            </h2>
            <p>I have a good
              <a href="https://en.wikipedia.org/wiki/Knowledge" target="_blank" title="More information" id="item2">
                <strong>
                  knowledge
                </strong>
              </a>
              of web design and conversion of these designs to html, css and programming</p>
          </div>
          <!-- end Intro column -->

          <div class="skills col-xs-12 col-sm-6 col-md-4">
            <h2>
              <strong>
                My Skills
              </strong>
            </h2>
            <ul class="list-group" id="skill-list">
              <li class="list-group-item">HTML (Currently Learning)</li>
              <li class="list-group-item">CSS (Currently Learning)</li>
              <li class="list-group-item">Fortran</li>
              <li class="list-group-item">Honeywell Control Language</li>
              <li class="list-group-item">ASPEN DMC Control Language</li>
            </ul>
          </div>
        </div>
        <!-- end row -->
      </div>
      <!-- end container -->
    </div>
    <!-- end container -->
    <!-- /end About Me -->
  <!--
  <% end %> -->

app/views/simple_pages/contact.html.erb
<!-- ****** C o n t a c t ****** -->
<div class="container" id="contact">
  <h1>Contact Us</h1>

  <div align="center">
    <%= render 'form' %>

    <h2>Address</h2>
    <p>Happy Lane 0815</p>
    <p>90210 Beverly Hills</p>
    <p>USA</p>

  </div>
</div>

app/views/simple_pages/landing_page.html.erb
<div class="row slider">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">

      <% @products.each_with_index do |product, index| %>
        <li data-target="#carousel-example-generic" data-slide-to="<%= index %>" class="<%= "active" if product == @products.first %>"></li>
      <% end %>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <% @products.each do |product| %>
        <div class="item<%= " active" if product == @products.first %>">
          <div align="center">
            <%= image_tag(product.image_url, class: "img-responsive") %>
          </div>
          <div class="carousel-caption">
            <h3><%= product.name %></h3>
            <p><%= product.description %></p>
          </div>
        </div>
      <% end %>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<h2>
  <strong>Featured Product:</strong>
</h2>
<div align="center">
  <h3><%= @featured_product.name %></h3>
  <%= image_tag(@featured_product.image_url, class: "img-product") %>
</div>
<div align="center">
  <%= link_to "Show Product", product_path(@featured_product) %>
</div>

app/views/simple_pages/thank_you.html.erb
<div class="container">
  <h1>Thank you</h1>
  <div class="panel panel-default">
    <div class="panel-body">
      <p>
        We have received your message and will respond as soon as possible.</p>
    </div>
    <!-- / panel-body -->
  </div>
  <!-- / panel -->
</div>