config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }

  resources :products do
    resources :comments
  end
  resources :users
  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/landing_page'
  post 'simple_pages/thank_you'
  root 'simple_pages#landing_page'
  post 'payments/create'

  resources :orders, only: %i[index show create destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :image_url, presence: true
  validates :colour, presence: true
  validates :price, presence: true

  has_many :orders
  has_many :comments
  def self.search(search_term)
    like_string = Rails.env.production? ? "ilike" : "LIKE"
    Product.where("name #{like_string} ?", "%#{search_term}%")
  end

  def highest_rating_comment
    comments.rating_desc.first.rating
  end

  def lowest_rating_comment
    comments.rating_asc.first.rating
  end

  def average_rating
    comments.average(:rating).to_f
  end

  def views
    $redis.get("product:#{id}")
  end

  def viewed!
    $redis.incr("product:#{id}")
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
    # assuming you load the @product in prepare_product
    #viewed uses redis server to git number pf product viewers
    @product.viewed!
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.'}
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.'}
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html do
        redirect_to products_url, notice: 'Product was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :description, :image_url, :colour, :price)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
  <% @comments.each do |comment| %>
    <%= render comment %>
  <% end %>
</div>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
  <p>
    <%= f.label :body, "Comments" %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <div class="rating"></div>
  </p>
  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
  <div class="card col-xs-12 col-sm-6 col-md-4 col-lg-2">
    <%= image_tag(product.image_url, class: "img-product") %>
    <div class="details">
      <h4>
        <b><%= product.name %></b>
      </h4>
      <p><%= product.description %></p>
      <p><%= product.colour %></p>
      <strong><%= product.price %>$</strong>
      <p><%= link_to 'Show', product %>
        |
        <%= link_to 'Edit', edit_product_path(product) %>
        |
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>

    </div>
  </div>
  <!-- /col -->
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'shared/form', product: @product %>

<div align="center">
  <%= link_to 'Show', @product %>
  |
  <%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="titlePage">Products</h1>

<br>

<div class="container">
  <div class="row">
    <% cache(cache_key_for_products) do %>
      <%= render @products %>
    <% end %>
  </div>
</div>

<div class="newProduct">
  <a href='<%= new_product_path %>'>
    <span class="glyphicon glyphicon-plus-sign"></span></a>

  <%= link_to 'New Product', new_product_path %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'shared/form', product: @product %>

<div align="center">
  <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="container">
  <h1>
    <strong>Product</strong>
  </h1>

  <div class="container description" align="center">
    <div class="row" data-product-id="<%= @product.id %>">
      <% cache @product do %>
        <div class="col-xs-12 col-sm-6 col-md-6">
          <%= image_tag(@product.image_url, class: "img-details product img-zoom", data_zoom_images:@product.image_url) %>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6">
          <p class="nameP">
            <strong>Name:</strong>
            <%= @product.name %>
          </p>

          <p>
            <strong>Description:</strong>
            <%= @product.description %>
          </p>

          <p>
            <strong>Color:</strong>
            <%= @product.colour %>
          </p>

          <p>
            <strong>price:</strong>
            <%= @product.price %>
          </p>

          <%= button_to 'Order Now', orders_path(product_id: @product.id, total: @product.price), class: "btn btn-primary" %>

          <p>Average Rating:
            <small>(<%= @product.comments.count%>
              reviews)</small>
            <div class="rated" id="average-rating" data-score="<%= @product.average_rating %>"></div>
          </p>

        <% end %>
        <%= form_with(url: '/payments/create') do |form| %>
        <%= form.hidden_field :product_id, :value => @product.id %>
        <%= render partial: "shared/stripe_checkout_button" %>
      <% end %>

      <h4>
        Views:
        <span class="badge">
          <%= @product.views %>
        </span>
      </h4>
      <hr>

      <%= link_to 'Edit', edit_product_path(@product) %>
      |
      <%= link_to 'Back', products_path %>
    </div>
  </div>
  <%= render 'new_comment' %>
  <br>
  <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
  <%= render 'comments' %>

  <div class="pagination">
    <%= will_paginate @comments %>
  </div>

  <!-- end about -->
</div>
<!-- end container -->
</div>